# Generated by Django 5.2.4 on 2025-09-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('profile_photo', models.ImageField(upload_to='profiles/')),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
